name: stem_email_service_example
description: Email notification service example using Stem task queue.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  mailer: ^6.1.0
  stem:
    path: ../..
  stem_cli:
    path: ../../../stem_cli
  stem_redis:
    path: ../../../stem_redis

dependency_overrides:
  stem:
    path: ../..
  stem_redis:
    path: ../../../stem_redis
  stem_sqlite:
    path: ../../../stem_sqlite
  stem_postgres:
    path: ../../../stem_postgres
