name: stem_sqlite
description: SQLite broker and result backend for Stem.
version: 0.1.1
repository: https://github.com/kingwill101/stem
resolution: workspace
environment:
  sdk: ^3.9.2

dependencies:
  artisanal: ^0.1.2
  collection: ^1.19.1
  contextual: ^2.2.0
  meta: ^1.18.0
  ormed: ^0.1.0
  ormed_sqlite: ^0.1.0
  path: ^1.9.1
  stem: ^0.1.0
  uuid: ^4.5.2

dev_dependencies:
  build_runner: ^2.10.5
  coverage: ^1.15.0
  lints: ^6.0.0
  stem_adapter_tests: ^0.1.0
  test: ^1.29.0
  very_good_analysis: ^10.0.0
