name: stem_sqlite
description: SQLite broker and result backend for Stem.
version: 0.1.0-dev
repository: https://github.com/kingwill101/stem
resolution: workspace
environment:
  sdk: ^3.9.2

dependencies:
  artisanal: ^0.1.0-dev+4
  collection: ^1.18.0
  meta: ^1.17.0
  ormed: ^0.1.0-dev+6
  ormed_sqlite: ^0.1.0-dev+6
  path: ^1.9.1
  stem: ^0.1.0-dev

dev_dependencies:
  build_runner: ^2.10.4
  lints: ^6.0.0
  stem_adapter_tests: ^0.1.0-dev
  test: ^1.26.3
  very_good_analysis: 
