name: stem_sqlite
description: SQLite broker and result backend for Stem.
version: 0.1.0-alpha.4
repository: https://github.com/kingwill101/stem
resolution: workspace
environment:
  sdk: ^3.9.2

dependencies:
  ormed: ^0.1.0-dev+6
  ormed_sqlite: ^0.1.0-dev+6
  args: ^2.6.0
  path: ^1.9.1
  collection: ^1.18.0
  meta: ^1.17.0
  sqlite3: ^3.1.1
  stem: ^0.1.0-alpha.4

dev_dependencies:
  build_runner: ^2.10.4
  lints: ^6.0.0
  test: ^1.26.3
  stem_adapter_tests: ^0.1.0-alpha.4
