name: stem_and_friends
environment:
  sdk: ">=3.9.2 <4.0.0"
workspace:
  - packages/stem
  - packages/stem_builder
  - packages/stem_sqlite
  - packages/stem_adapter_tests
  - packages/stem_redis
  - packages/stem_postgres
  - packages/stem_cli
  - packages/stem/example/docs_snippets
  - packages/cloud/stem_cloud_protocol
  - packages/cloud/stem_cloud_gateway
  - packages/cloud/stem_cloud_worker
dev_dependencies:
  coverage: ^1.15.0
  very_good_analysis: ^10.0.0
dependency_overrides:
  timezone: 0.11.0
  pointycastle: ^4.0.0
