name: stem_and_friends
publish_to: none
environment:
  sdk: ">=3.9.2 <4.0.0"
workspace:
  - packages/stem
  - packages/stem_builder
  - packages/stem_sqlite
  - packages/stem_adapter_tests
  - packages/stem_redis
  - packages/stem_postgres
  - packages/stem_cli
dev_dependencies:
  coverage: ^1.15.0
  very_good_analysis: ^10.0.0
dependency_overrides:
  liquify: ^1.5.0
  timezone: 0.11.0
  pointycastle: ^4.0.0
