name: stem_and_friends
environment:
  sdk: ">=3.9.2 <4.0.0"
workspace:
  - packages/stem
  - packages/stem_sqlite
  - packages/stem_adapter_tests
  - packages/stem_redis
  - packages/stem_postgres
  - packages/stem_cli
dev_dependencies:
  lints: ^6.0.0
  very_good_analysis: ^10.0.0
