name: stem_microservice_enqueuer
description: HTTP API that enqueues Stem tasks using Redis.
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  stem: any
  stem_redis: any

dev_dependencies:
  lints: ^6.0.0

dependency_overrides:
  stem:
    path: ../../..
  stem_redis:
    path: ../../../../stem_redis