name: stem_cli
description: Command-line tooling for Stem that orchestrates Redis and Postgres adapters.
version: 0.1.0
repository: https://github.com/kingwill101/stem
resolution: workspace
environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  artisanal: ^0.1.2
  stem: ^0.1.0
  stem_redis: ^0.1.0
  stem_postgres: ^0.1.0
  stem_sqlite: ^0.1.0
  redis: ^4.0.0
  postgres: ^3.5.9
  async: ^2.13.0
  collection: ^1.19.1
  path: ^1.9.1
  yaml: ^3.1.3

dev_dependencies:
  coverage: ^1.15.0
  lints: ^6.0.0
  test: ^1.29.0
  very_good_analysis: ^10.0.0

false_secrets:
  - docker/testing/postgres/certs/server.key
