name: stem_annotated_workflows
description: Example app using annotated Stem workflows and tasks.
publish_to: 'none'
version: 0.0.1
resolution: workspace

environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  stem: ^0.1.0

dev_dependencies:
  build_runner: ^2.10.4
  stem_builder: ^0.1.0
