name: stem_postgres
description: Postgres broker, result backend, and scheduler utilities for Stem.
version: 0.1.0-alpha.4
repository: https://github.com/kingwill101/stem
resolution: workspace
environment:
  sdk: ">=3.9.2 <4.0.0"

dependencies:
  postgres: ^3.5.9
  stem: ^0.1.0-alpha.4
  collection: ^1.18.0
  path: ^1.9.1
  uuid: ^4.5.1


dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
  stem_adapter_tests: ^0.1.0-alpha.4
  stem_cli: ^0.1.0-alpha.4
